package pojo;
// Generated 30/05/2018 11:24:50 AM by Hibernate Tools 4.3.1



/**
 * Seguimiento generated by hbm2java
 */
public class Seguimiento  implements java.io.Serializable {


     private Integer id;
     private Paciente paciente;
     private String seguimiento;

    public Seguimiento() {
    }

	
    public Seguimiento(Paciente paciente) {
        this.paciente = paciente;
    }
    public Seguimiento(Paciente paciente, String seguimiento) {
       this.paciente = paciente;
       this.seguimiento = seguimiento;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }
    public String getSeguimiento() {
        return this.seguimiento;
    }
    
    public void setSeguimiento(String seguimiento) {
        this.seguimiento = seguimiento;
    }




}


